# Author: Celia Xiao

ARG     BASE_IMAGE_NAME
ARG     BASE_IMAGE_VERSION

# base
FROM    $BASE_IMAGE_NAME:$BASE_IMAGE_VERSION

# copy source code to workdir
COPY    . /client

# change the active directory
WORKDIR /client

# build app
RUN     yarn build

