version: '3.6'

services:
  go-todo:
    restart: always
    container_name: go-todo
    image: go-todo:latest
    network_mode: "host"
    ports:
      - 8080:8080
    environment:
        DB_URI: ${DB_URI}
        DB_NAME: ${DB_NAME}
        DB_COLLECTION_NAME: ${DB_COLLECTION_NAME}
    env_file:
      - .env
    command: ./go-server

networks:
  default:
    external:
      name: prod

